[package]
name = "nrtm-preparse"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.9.0"
pest_derive = "2.9.0"
tokio-util = { version = "0.7.19", optional = true, features = ["codec"] }


[features]
default = [ "async-streaming" ]
async-streaming = [ "dep:tokio-util" ]

[dev-dependencies]
tokio = { version = "1.53.1", features = ["fs", "macros", "rt" ] }
tokio-stream = "0.1.19"
tokio-test = "0.4.5"
